title: Chengfeng Feng
description: Satellite DA, Vball Lover
site_title: '@RoyCaitSith - Chengfeng Feng'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: RoyCaitSith
email: ROY.FENG@utah.edu
instagram_username: roy_fung_2018
twitter_username: roy_caitsith

# absolute or relative
profile_picture: assets/images/pp.jpg
